### ISSUE TITLE
Upload & Backup all datasets regardless of being active

### ISSUE THREAD

**Issue by NathanNovak** [StraboSpot/StraboSpot2#348]
Need to make sure all dataset data is being backed up to the device instead of just selected or active datasets per Doug's request from testing in the field.

**Comment by jessicagood** [comment]
Currently if SpotA is assigned a Tag but then a different dataset is uploaded (and thus the project properties which includes the Tags is uploaded too) then the server will have the id for SpotA listed in the Tags but the server will not have SpotA itself since SpotA's dataset was never uploaded.

Uploading all datasets regardless of active status will eliminate this problem.

**Comment by jessicagood** [comment]
Fixed in commit #467
