### ISSUE TITLE
Active dataset changes unexpectedly

### ISSUE THREAD

**Issue by eschermer** [StraboSpot/StraboSpot2#459]
**Describe the bug**
When you turn on a second (or more) dataset to view it, the active dataset changes to that dataset.

**To Reproduce**
Are you able to reproduce the problem in a new project after restarting the app?
Yes

1. Go to active project
2. Click on list of datasets (I already have the desired dataset active but want to view another one temporarily)
3. Scroll down to the dataset I want to view, click the green dot
4. this new dataset becomes the active one. 
5. I didn't notice the blue checkmark changed, and went back to collecting data in the new dataset when I intended to collect it in the original desired dataset. 

**Expected behavior**
I would like the original dataset to stay the active one, or for there to be a default dataset that doesn't change.  I have mistakenly saved spots to the wrong dataset and it is difficult/time consuming to copy them over. 

**Screenshots**

**Smartphone (please complete the following information):**
 - Device: Ipad mini 6
 - OS: IOS 15.5
 - StraboSpot Version 1.24.0

**Additional context**
We have several old and current workers' datasets in the project and don't want to corrupt or add new info to those old datasets.  We want to hide them for much of the work because it makes the map too busy otherwise, but occasionally want to view them to check sample sites, e.g.  Viewing a new dataset shouldn't change the active dataset.  I can work around this issue but it is annoying to make the mistake and have to copy spots to the active dataset (by manually re-entering them) and delete them from the old one.

**Comment by NathanNovak** [comment]
Hi @eschermer. I will take a look at this and see about placing an option to stay with the current dataset in view or "fly" to the newly selected one.

**Comment by NathanNovak** [comment]
Hi @eschermer,

So I made a change that I hope will help when changing datasets (see images below).   There will now be a modal that pops up asking if you would like to make the newly switched-on dataset the current one. The map will still "fly" to show all the datasets in the screen view but you will have better control over which dataset is the current one for data entry.  


![IMG_FB48A51D258E-1](https://user-images.githubusercontent.com/35514146/180476190-df8c0923-f64c-4286-a6a2-9339554d8752.jpeg)

![IMG_0289](https://user-images.githubusercontent.com/35514146/180325284-f107b185-8537-4835-9042-6cccfb8e7109.PNG)

Fixed with commit 8cef24209aa47be09fe79b625a9893331ce32855

**Comment by eschermer** [comment]
Thank you !

Sent from my iPhone

On Jul 22, 2022, at 9:52 AM, Nathan Novak ***@***.***> wrote:

﻿
You don't often get email from ***@***.*** Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

Closed #459<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FStraboSpot%2FStraboSpot2%2Fissues%2F459&data=05%7C01%7Cschermer%40wwu.edu%7Cfc01b6974edd44080c1c08da6bfa379c%7Cdc46140ce26f43efb0ae00f257f478ff%7C0%7C0%7C637941019683008509%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=YcxHzDnsv0ZTe7i4j7Yaf84ZrqrfmsJ3Xj5qct1YybA%3D&reserved=0> as completed.
