### ISSUE TITLE
Auto save the notes

### ISSUE THREAD

**Issue by panamint55** [StraboSpot/StraboSpot2#508]
It would be a good idea if somebody is entering notes and then wants to go to the overview again or to some other page that it auto saves the notes. right now there's a save button and that seems like it's redundant or unneeded. I think we should just auto save the notes.

**Comment by NathanNovak** [comment]
@panamint55 when navigating off of the Note page there should be a dialogue box asking the user if they want to save the changes, if there are any.

**Comment by NathanNovak** [comment]
@panamint55 sure thing we can remove the buttons on top of the note space. If we save each keystroke, similar to changing the spot name, it could bog down the app because of the amount of times it sends the keystroke to redux. Name changes are typically short compared to notes.

We can make it so the user writes the note and it is saved to a local state then the entire note up to that point dispatched to redux on exit of the Notes page.  we can also add a pop up message confirming that it saved to the user on exit

**Comment by panamint55** [comment]
Got it.  That makes sense to do.

Doiug

From: Nathan Novak ***@***.***>
Reply-To: StraboSpot/StraboSpot2 ***@***.***>
Date: Friday, July 7, 2023 at 9:45 AM
To: StraboSpot/StraboSpot2 ***@***.***>
Cc: Doug Walker ***@***.***>, Mention ***@***.***>
Subject: Re: [StraboSpot/StraboSpot2] Auto save the notes (Issue #508)


@panamint55<https://github.com/panamint55> sure thing we can remove the buttons on top of the note space. If we save each keystroke, similar to changing the spot name, it could bog down the app because of the amount of times it sends the keystroke to redux. Name changes are typically short compared to notes.

We can make it so the user writes the note and it is saved to a local state then the entire note up to that point dispatched to redux on exit of the Notes page. we can also add a pop up message confirming that it saved to the user on exit
